import Header from "@/components/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const alpino = localFont({
  src: "../public/fonts/Alpino-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-alpino",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alpino.variable} h-screen overflow-x-hidden bg-[#d2f4fb]`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
